<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>Exe</OutputType>
		<WarnOn>3390;$(WarnOn)</WarnOn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.11.0" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="AuthorizationRequirementResolverTests.fs" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\AuthZI.Security\AuthZI.Security.fsproj" />
	</ItemGroup>

</Project>