# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  - master

variables:
  shouldDeploy: true
  BuildConfiguration: Release

stages:
  - stage: Build
    displayName: Build stage
    pool:
      name: Azure Pipelines
    variables:
      - group: Default
    jobs:
    - job: Build_Solution
      displayName: Whole solution build process
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build solution AuthZI.sln'
        inputs:
          command: build
          projects: 'AuthZI.sln'
          configuration: '$(buildConfiguration)'

      # Run Tests
      - task: DotNetCoreCLI@2
        displayName: 'Run Integration Tests'
        inputs:
          command: test
          projects: |
            test/Authzi.Security.IntegrationTests
            test/Authzi.Tests.MicrosoftOrleans/DuendeSoftware.IdentityServer
            test/Authzi.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraID.NET8.0
            test/Authzi.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraExternalID.NET8.0
            publishTestResults: true
        env: 
          microsoftEntraIdCredentials: $(MICROSOFT_ENTRA_ID_CREDENTIALS)
          microsoftEntraExternalIdCredentials: $(MICROSOFT_ENTRA_EXTERNAL_ID_CREDENTIALS)

##################### Packing Artifacts Stages #####################

  - stage: Packing_Artifacts_Testing
    displayName: Packing artifacts testing
    dependsOn:
    jobs:
    - deployment: Deploy_Artifacts_Testing
      displayName: Deploy testing artifacts in Azure Artifacts
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      pool:
        name: Azure Pipelines
      environment: 'Testing'
      strategy: 
        runOnce:
          deploy:
            steps:
            - checkout: self
              fetchTags: true
            - template: packing-artifacts.yml
              parameters:
                vstsFeedName: 'AuthZI/Testing'

  - stage: Packing_Artifacts_Staging
    displayName: Packing artifacts staging
    dependsOn: Build
    jobs:
    - deployment: Deploy_Artifacts_Staging
      displayName: Deploy staging artifacts in Azure Artifacts
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      pool:
        name: Azure Pipelines
      environment: 'Staging'
      strategy: 
        runOnce:
          deploy:
            steps:
            - checkout: self
              fetchTags: true
            - template: packing-artifacts.yml
              parameters:
                vstsFeedName: 'AuthZI/Staging'