# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  - master

variables:
  shouldDeploy: true
  BuildConfiguration: Release

stages:
  - stage: Build
    displayName: Build stage
    pool:
      name: Azure Pipelines
    variables:
      - group: Default
    jobs:
    - job: Build_Solution
      displayName: Whole solution build process
      steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK 9.0.x'
        inputs:
          packageType: 'sdk'
          version: '9.0.x'
      - task: DotNetCoreCLI@2
        displayName: 'Build solution AuthZI.sln'
        inputs:
          command: build
          projects: 'AuthZI.sln'
          configuration: '$(buildConfiguration)'
    
    - job: Run_Tests_DotNet8
      displayName: Run Tests .NET 8.0.x
      dependsOn: Build_Solution
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Run Integration Tests'
        inputs:
          command: test
          projects: |
            test/AuthZI.Tests.Security
            test/AuthZI.Tests.MicrosoftOrleans/Duende.IdentityServer
            test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraID.NET8.0
            test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraExternalID.NET8.0
            publishTestResults: true
        env: 
          microsoftEntraIdCredentials: $(MICROSOFT_ENTRA_ID_CREDENTIALS)
          microsoftEntraExternalIdCredentials: $(MICROSOFT_ENTRA_EXTERNAL_ID_CREDENTIALS)
    
    - job: Run_Tests_DotNet9
      displayName: Run Tests .NET 9.0.x
      dependsOn: Build_Solution
      steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK 9.0.x'
        inputs:
          packageType: 'sdk'
          version: '9.0.x'
      - task: DotNetCoreCLI@2
        displayName: 'Run Integration Tests'
        inputs:
          command: test
          projects: |
            test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraID.NET9.0
            test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraExternalID.NET9.0
            publishTestResults: true
        env: 
          microsoftEntraIdCredentials: $(MICROSOFT_ENTRA_ID_CREDENTIALS)
          microsoftEntraExternalIdCredentials: $(MICROSOFT_ENTRA_EXTERNAL_ID_CREDENTIALS)

##################### Packing Artifacts Stages #####################

  - stage: Packing_Artifacts_Testing
    displayName: Packing artifacts testing
    dependsOn:
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Azure Pipelines
    jobs:
    - deployment: Deploy_Artifacts_Testing
      displayName: Deploy testing artifacts in Azure Artifacts
      environment: 'Testing'
      strategy: 
        runOnce:
          deploy:
            steps:
            - checkout: self
              fetchTags: true
            - template: packing-artifacts.yml
              parameters:
                vstsFeedName: 'AuthZI/Testing1'

  - stage: Packing_Artifacts_Staging
    displayName: Packing artifacts staging
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Azure Pipelines
    jobs:
    - deployment: Deploy_Artifacts_Staging
      displayName: Deploy staging artifacts in Azure Artifacts
      environment: 'Staging'
      strategy: 
        runOnce:
          deploy:
            steps:
            - checkout: self
              fetchTags: true
            - template: packing-artifacts.yml
              parameters:
                vstsFeedName: 'AuthZI/Staging1'