name: Default CI Workflow
run-name: Default CI Workflow by ${{ github.actor }}
on: [push]
jobs:
##################### Build Solution ##################### 
  Build_Solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore AuthZI.sln
      - name: Build_Solution
        run: dotnet build AuthZI.sln --configuration Release --no-restore

##################### Launch End To End Testing ##################### 
  End_To_End_Testing:
    runs-on: ubuntu-latest
    needs: [ Build_Solution ]
    env:
      microsoftEntraIdCredentials: '${{ secrets.MICROSOFT_ENTRA_ID_CREDENTIALS }}'
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          dotnet test test/Authzi.Security.IntegrationTests