name: Default CI Workflow
run-name: Default CI Workflow by ${{ github.actor }}
on: [push]
jobs:
##################### Build Solution ##################### 
  Build_Solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore AuthZI.sln
      - name: Build_Solution
        run: dotnet build AuthZI.sln --configuration Release --no-restore

##################### Launch Integration Testing ##################### 
  Integration_Testing:
    runs-on: ubuntu-latest
    needs: [ Build_Solution ]
    env:
      microsoftEntraIdCredentials: '${{ secrets.MICROSOFT_ENTRA_ID_CREDENTIALS }}'
      microsoftEntraExternalIdCredentials: '${{ secrets.MICROSOFT_ENTRA_EXTERNAL_ID_CREDENTIALS }}'
      microsoftAzureADB2CCredentials: '${{ secrets.MICROSOFT_AZURE_ADB2C_CREDENTIALS }}'
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          dotnet test test/AuthZI.Tests.Security
          dotnet test test/AuthZI.Tests.MicrosoftOrleans/DuendeSoftware.IdentityServer
          dotnet test test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraID.NET8.0
          dotnet test test/AuthZI.Tests.MicrosoftOrleans/MicrosoftEntra/MicrosoftEntraExternalID.NET8.0